spring:
  datasource:
    url: jdbc:h2:~/footballManager/db/footballManager;CIPHER=AES;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: filepwd userpwd
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


logging.file: ~/footballManager/logs/
